TITLE = "Документация медицинского кабинета"

SHEET_SIZE = 1280, 640

FONT_FAMILY = "Courier"

FONT_SIZE = "12pt"

BACKGROUND_SHEET_COLOR = "#80C060"

BACKGROUND_WIDGET_COLOR = "#90D070"

SELECT_BAR_WIDTH = 200

CHECKBOXES_VERTICAL = 20

CHECKBOXES_HORIZONTAL = 3
